### PR TITLE
Put main package in src directory

### LINKED ISSUE #23: Put main package in src directory
The problem of it loading the local package rather than the installed one is a common problem and the most suggested fix is to put your actual package in a (non-python-package) `src/` folder. So you'd have:

```
corrcal/
    setup.py
    src/
        corrcal/
            __init__.py
```

This will also help in testing (because pytest will by default pick up the local package rather than the installed one, which is _usually_ not what you want!)

See https://blog.ionelmc.ro/2014/05/25/python-packaging/ for example.

### PR DESCRIPTION
**Pull request by piyanatk**
This PR fixes #23.

The new structure is not Python standard but is commonly used, and should prevent loading of compiled C library from the local development directory.

### CODE REVIEW

**Comment by piyanatk** [comment]
@steven-murray @ronniyjoseph Can either of you review this PR please?

**Comment by steven-murray** [comment]
@piyanatk I don't think the `data/` folder is in the right place -- it's not being installed on my system.

**Comment by piyanatk** [comment]
@steven-murray  https://github.com/UKZN-Astronomy/corrcal/pull/30/commits/404d32fb4e75e9ec5f9dddc70ba310c2daf05262 should fix that issue now.

**Review by steven-murray — APPROVED** [review]
All looks good.

**Comment by ronniyjoseph** [comment]
Sorry, I didn't have the time to look at it.

So on my install I had to change the path for LIB_LOC = glob(site.getsitepackages()[0] + "/corrcal*/corrcal/c_corrcal*.so")[0] in wrapper.py

Because the c_corrcal.so file is now one folder deeper.

**Pull request merged**
